import type { LegalSection } from "./LegalDocument";

export type LegalDocumentKey = "legal" | "terms" | "privacy" | "cookies" | "withdrawal";
type DocumentContent = { title: string; description: string; updated: string; sections: LegalSection[] };

const company = {
  fr: "Unisis Development SRL, exploitant la marque PexxaFloor — Brusselstraat 107 D, 1702 Groot-Bijgaarden, Belgique — BCE/TVA BE 0871.407.121 — info@pexxafloor.be — +32 2 343 92 00.",
  en: "Unisis Development SRL, trading under the PexxaFloor brand — Brusselstraat 107 D, 1702 Groot-Bijgaarden, Belgium — company/VAT number BE 0871.407.121 — info@pexxafloor.be — +32 2 343 92 00.",
  nl: "Unisis Development SRL, handelend onder het merk PexxaFloor — Brusselstraat 107 D, 1702 Groot-Bijgaarden, België — KBO/btw BE 0871.407.121 — info@pexxafloor.be — +32 2 343 92 00.",
};

const content: Record<"fr" | "en" | "nl", Record<LegalDocumentKey, DocumentContent>> = {
  fr: {
    legal: {
      title: "Mentions légales",
      description: "Informations relatives à l’éditeur, à l’hébergement et à l’utilisation du site PexxaFloor.",
      updated: "Dernière mise à jour : 14 août 2026",
      sections: [
        { title: "Éditeur et vendeur", paragraphs: [company.fr, "Le vendeur peut être contacté aux coordonnées ci-dessus pour toute question relative au site, aux produits ou à une commande."] },
        { title: "Hébergement", paragraphs: ["Le site est hébergé par Vercel Inc. Les données applicatives sont notamment traitées à l’aide des services Supabase. Les prestataires techniques sont encadrés conformément à la politique de confidentialité."] },
        { title: "Propriété intellectuelle", paragraphs: ["Les textes, visuels, logos, configurateurs, documents et éléments du site sont protégés. Toute reproduction, adaptation ou exploitation sans autorisation écrite préalable est interdite, sauf exception prévue par la loi."] },
        { title: "Disponibilité et responsabilité", paragraphs: ["PexxaFloor s’efforce de fournir des informations exactes et de maintenir le site accessible. Une interruption, une erreur technique ou une information manifestement incorrecte peut néanmoins survenir. Les informations techniques ne remplacent pas l’étude d’un professionnel lorsque la nature du chantier l’exige."] },
        { title: "Liens et services externes", paragraphs: ["Le site utilise ou peut rediriger vers des services tiers tels que Stripe, Google Maps, Supabase et Resend. Leurs propres conditions peuvent s’appliquer lors de leur utilisation."] },
      ],
    },
    terms: {
      title: "Conditions générales de vente",
      description: "Conditions applicables aux commandes passées sur le site PexxaFloor par des consommateurs ou des clients professionnels.",
      updated: "Version applicable à partir du 14 août 2026",
      sections: [
        { title: "1. Vendeur et champ d’application", paragraphs: [company.fr, "Ces conditions régissent les ventes réalisées sur le site. Les dispositions impératives de protection du consommateur s’appliquent uniquement aux clients agissant à des fins non professionnelles. Toute condition particulière expressément acceptée prévaut sur le présent texte en cas de contradiction."] },
        { title: "2. Produits et configurateur", paragraphs: ["Les caractéristiques essentielles sont présentées sur les fiches produits. Le configurateur de pack fournit une composition calculée à partir des données saisies par le client. Celui-ci reste responsable de l’exactitude des dimensions, paramètres et contraintes communiqués. En cas de doute technique, il doit demander conseil avant la commande."] },
        { title: "3. Prix", paragraphs: ["Les prix sont affichés en euros, HTVA et TVAC lorsqu’applicable. Le prix total, les taxes et les éventuels frais de livraison sont récapitulés avant la confirmation de la commande. PexxaFloor peut modifier ses prix pour l’avenir, mais applique le prix confirmé lors de la commande, sous réserve de la correction d’une erreur manifeste."] },
        { title: "4. Commande", paragraphs: ["Le client vérifie son panier, son identité et son adresse avant de payer. La commande devient ferme après confirmation du paiement et envoi de la confirmation, sous réserve de disponibilité et des contrôles antifraude usuels. PexxaFloor peut refuser ou annuler une commande frauduleuse, manifestement erronée ou impossible à exécuter, avec remboursement des sommes encaissées."] },
        { title: "5. Paiement", paragraphs: ["Le paiement est traité par Stripe au moyen des méthodes proposées lors du checkout. PexxaFloor ne reçoit pas les données complètes de la carte bancaire. La commande n’est préparée qu’après confirmation du paiement."] },
        { title: "6. Livraison", paragraphs: ["Les zones, modes, prix et délais estimés de livraison sont indiqués sur le site ou avant paiement. Les délais sont indicatifs sauf engagement exprès. Le client doit fournir une adresse accessible et vérifier les colis à la réception. Tout dommage apparent ou produit manquant doit être signalé rapidement avec des photographies et les références de la commande."] },
        { title: "7. Rétractation des consommateurs", paragraphs: ["Le consommateur dispose en principe de 14 jours à compter de la réception pour notifier sa rétractation, sans devoir la motiver. Il renvoie ensuite les biens dans les 14 jours, avec les frais directs de retour à sa charge sauf indication contraire. Les modalités et le formulaire figurent sur la page Rétractation et retours.", "Les exceptions légales s’appliquent notamment aux biens fabriqués selon les spécifications du consommateur ou clairement personnalisés. Une simple sélection parmi des options standard ne rend pas automatiquement le produit personnalisé."] },
        { title: "8. Garanties", paragraphs: ["Le consommateur bénéficie de la garantie légale de conformité prévue par le droit belge, en principe pendant deux ans à compter de la délivrance d’un bien neuf. Cette garantie ne couvre pas l’usure normale, une installation non conforme, un usage inadapté ou un dommage causé après la livraison. Les clients professionnels bénéficient des garanties impératives applicables et des éventuelles garanties fabricant."] },
        { title: "9. Responsabilité", paragraphs: ["Aucune clause ne limite une responsabilité qui ne peut légalement l’être. Pour les clients professionnels, et dans la mesure permise par la loi, la responsabilité est limitée aux dommages directs prévisibles et au montant de la commande concernée. Le respect des prescriptions d’installation, de sécurité et des règles de l’art incombe à l’installateur."] },
        { title: "10. Réclamations et litiges", paragraphs: ["Toute réclamation peut être envoyée à info@pexxafloor.be. Le consommateur peut également contacter le Service de Médiation pour le Consommateur, Boulevard du Roi Albert II 8 boîte 1, 1000 Bruxelles (mediationconsommateur.be). Le droit belge s’applique, sans priver le consommateur des protections impératives de son pays de résidence. Les juridictions compétentes sont déterminées par les règles légales applicables."] },
      ],
    },
    privacy: {
      title: "Politique de confidentialité et RGPD",
      description: "Cette politique explique quelles données personnelles sont traitées, pourquoi elles le sont et quels sont vos droits.",
      updated: "Dernière mise à jour : 14 août 2026",
      sections: [
        { title: "Responsable du traitement", paragraphs: [company.fr, "Pour toute question ou demande relative à vos données : info@pexxafloor.be."] },
        { title: "Données traitées", items: ["Compte et identité : nom, e-mail, identifiant, données de connexion et rôle.", "Commande et livraison : panier, produits, prix, adresse, téléphone, historique et statut.", "Compte PRO : entreprise, numéro de TVA, activité, coordonnées et pièces communiquées.", "Devis : configuration, référence de projet et informations client saisies par le professionnel.", "Paiement : identifiants et statut transmis par Stripe, sans conservation du numéro complet de carte.", "Données techniques : journaux de sécurité, adresse IP, appareil, langue et informations nécessaires au fonctionnement."] },
        { title: "Finalités et bases juridiques", items: ["Créer le compte, préparer une commande, livrer et assurer le service après-vente : exécution du contrat ou mesures précontractuelles.", "Facturation, comptabilité, garanties et réponses aux autorités : obligation légale.", "Sécurité, prévention de la fraude et amélioration du service : intérêt légitime, après mise en balance des droits.", "Enregistrement facultatif d’une adresse ou fonctionnalités non essentielles : consentement lorsque celui-ci est requis."] },
        { title: "Destinataires et sous-traitants", paragraphs: ["Les données sont accessibles aux personnes autorisées chez PexxaFloor et, selon le besoin, à Supabase (base et authentification), Vercel (hébergement), Stripe (paiement), Resend (e-mails), Google Maps (adresse), ainsi qu’aux transporteurs, comptables et autorités légalement habilitées. Seules les données nécessaires leur sont communiquées."] },
        { title: "Transferts internationaux", paragraphs: ["Certains prestataires peuvent traiter des données hors de l’Espace économique européen. Ces transferts doivent reposer sur une décision d’adéquation, des clauses contractuelles types ou une autre garantie reconnue par le RGPD."] },
        { title: "Durées de conservation", paragraphs: ["Les données sont conservées pendant la durée nécessaire à chaque finalité. Les documents de commande, facturation et comptabilité sont gardés pendant la durée légale applicable, généralement jusqu’à dix ans. Le compte est conservé tant qu’il est actif puis supprimé ou anonymisé, sauf obligation légale ou litige. Les adresses facultatives restent enregistrées jusqu’à leur suppression par le client. Les journaux techniques sont conservés pour une durée proportionnée à la sécurité."] },
        { title: "Vos droits", paragraphs: ["Vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou l’opposition lorsque les conditions légales sont remplies, et retirer votre consentement sans effet rétroactif. Une preuve d’identité peut être demandée en cas de doute raisonnable. Vous pouvez introduire une plainte auprès de l’Autorité de protection des données belge : autoriteprotectiondonnees.be."] },
        { title: "Sécurité", paragraphs: ["Des mesures techniques et organisationnelles sont utilisées : contrôle des rôles, politiques RLS Supabase, communications chiffrées, secrets côté serveur et limitation des accès. Aucun système ne pouvant offrir une sécurité absolue, tout incident est traité conformément aux obligations applicables."] },
      ],
    },
    cookies: {
      title: "Politique relative aux cookies",
      description: "Informations sur le stockage local et les services tiers utilisés par PexxaFloor.",
      updated: "Dernière mise à jour : 14 août 2026",
      sections: [
        { title: "Que sont les cookies ?", paragraphs: ["Un cookie ou stockage similaire permet à un site de mémoriser une information dans le navigateur. Certains sont indispensables à la connexion, à la sécurité et au panier ; d’autres nécessitent un consentement préalable."] },
        { title: "Technologies nécessaires", items: ["Supabase Auth : maintien sécurisé de la session et renouvellement des jetons.", "Stockage local du panier : conservation des articles entre deux pages ou visites.", "Préférence de langue et protections techniques nécessaires au fonctionnement."] },
        { title: "Services tiers", items: ["Stripe peut utiliser des technologies nécessaires à la sécurisation du paiement lorsque le checkout est ouvert.", "Google Maps Places reçoit les requêtes saisies dans le champ d’adresse et peut utiliser ses propres cookies ou identifiants.", "Vercel et Supabase peuvent produire des journaux techniques nécessaires à la sécurité et à la disponibilité."] },
        { title: "Votre choix", paragraphs: ["Les technologies strictement nécessaires ne peuvent pas être désactivées depuis le site. Les technologies non essentielles ne doivent être activées qu’après votre consentement lorsqu’il est légalement requis. Vous pouvez également supprimer ou bloquer les cookies dans les réglages de votre navigateur, au risque de limiter certaines fonctions."] },
        { title: "Contact", paragraphs: ["Pour toute question sur les cookies ou l’exercice de vos droits : info@pexxafloor.be."] },
      ],
    },
    withdrawal: {
      title: "Rétractation et retours",
      description: "Informations destinées aux consommateurs qui souhaitent retourner une commande à distance.",
      updated: "Dernière mise à jour : 14 août 2026",
      sections: [
        { title: "Délai de rétractation", paragraphs: ["Si vous êtes consommateur, vous disposez en principe de 14 jours à compter du jour où vous-même ou un tiers désigné prenez physiquement possession des biens. Pour une commande livrée séparément, le délai commence à la réception du dernier bien."] },
        { title: "Comment exercer ce droit", paragraphs: ["Avant l’expiration du délai, envoyez une déclaration dénuée d’ambiguïté à info@pexxafloor.be en mentionnant votre numéro de commande. Vous pouvez utiliser le modèle ci-dessous, sans que cela soit obligatoire."] },
        { title: "Modèle de formulaire", paragraphs: ["À l’attention de Unisis Development SRL / PexxaFloor, Brusselstraat 107 D, 1702 Groot-Bijgaarden, info@pexxafloor.be :\n\nJe vous notifie par la présente ma rétractation du contrat portant sur la vente des biens suivants : [produits].\nCommandés le / reçus le : [date].\nNom : [nom].\nAdresse : [adresse].\nDate : [date].\nSignature, uniquement en cas d’envoi papier : [signature]."] },
        { title: "Retour et remboursement", paragraphs: ["Les biens doivent être renvoyés au plus tard 14 jours après la notification, correctement protégés et, si possible, dans leur emballage d’origine. Les frais directs de retour sont à votre charge sauf accord contraire. Le remboursement comprend les paiements reçus et, lorsque la loi l’impose, le coût de la livraison standard. Il peut être différé jusqu’à récupération des biens ou réception d’une preuve d’expédition."] },
        { title: "Dépréciation et exceptions", paragraphs: ["Vous êtes responsable de la diminution de valeur résultant de manipulations allant au-delà de ce qui est nécessaire pour vérifier la nature et les caractéristiques du bien. Le droit ne s’applique pas dans les cas exclus par la loi, notamment aux biens réellement fabriqués selon vos spécifications ou clairement personnalisés. Contactez-nous avant tout retour afin de confirmer l’adresse et l’organisation pratique."] },
      ],
    },
  },
  en: {
    legal: { title: "Legal notice", description: "Information about the publisher, hosting and use of the PexxaFloor website.", updated: "Last updated: 14 August 2026", sections: [
      { title: "Publisher and seller", paragraphs: [company.en, "The seller can be contacted using the details above for any question about the website, products or an order."] },
      { title: "Hosting", paragraphs: ["The website is hosted by Vercel Inc. Application data is processed in particular using Supabase services. Technical providers are governed as described in the privacy policy."] },
      { title: "Intellectual property", paragraphs: ["The texts, visuals, logos, configurators, documents and website elements are protected. Reproduction, adaptation or use without prior written permission is prohibited, except where allowed by law."] },
      { title: "Availability and liability", paragraphs: ["PexxaFloor endeavours to provide accurate information and maintain access to the website. Interruptions, technical errors or manifestly incorrect information may nevertheless occur. Technical information does not replace a professional assessment where the project requires one."] },
      { title: "External services", paragraphs: ["The website uses or may redirect to third-party services such as Stripe, Google Maps, Supabase and Resend. Their own terms may apply."] },
    ] },
    terms: { title: "Terms and conditions of sale", description: "Terms applying to orders placed on PexxaFloor by consumers and professional customers.", updated: "Applicable from 14 August 2026", sections: [
      { title: "1. Seller and scope", paragraphs: [company.en, "These terms govern sales made through the website. Mandatory consumer protections apply only to customers acting outside their professional activity. Expressly agreed special terms prevail in case of conflict."] },
      { title: "2. Products and configurator", paragraphs: ["Essential characteristics are shown on product pages. The pack configurator calculates a composition from the information entered by the customer, who remains responsible for the accuracy of measurements, settings and constraints. Technical advice should be requested before ordering when in doubt."] },
      { title: "3. Prices", paragraphs: ["Prices are displayed in euros excluding and including VAT where applicable. The total, taxes and delivery costs are shown before confirmation. Future prices may change, but the confirmed order price applies unless there is an obvious error."] },
      { title: "4. Order and payment", paragraphs: ["The customer checks the basket, identity and address before paying. The order becomes binding after payment confirmation and the order confirmation, subject to availability and usual fraud checks. Payment is processed by Stripe; PexxaFloor does not receive full card details."] },
      { title: "5. Delivery", paragraphs: ["Areas, methods, charges and estimated times are shown on the website or before payment. Times are estimates unless expressly guaranteed. The customer must provide an accessible address, inspect parcels and promptly report visible damage or missing items with photographs and the order reference."] },
      { title: "6. Consumer withdrawal", paragraphs: ["Consumers generally have 14 days after receipt to notify withdrawal and a further 14 days to return the goods. Direct return costs are borne by the consumer unless stated otherwise. Statutory exceptions include goods made to the consumer’s specifications or clearly personalised; selecting standard options alone does not automatically make an item personalised."] },
      { title: "7. Guarantees", paragraphs: ["Consumers benefit from the Belgian statutory conformity guarantee, generally for two years after delivery of new goods. It does not cover normal wear, incorrect installation, unsuitable use or damage after delivery. Professional customers benefit from mandatory and applicable manufacturer guarantees."] },
      { title: "8. Liability", paragraphs: ["Nothing excludes liability that cannot legally be excluded. For professional customers, to the extent permitted by law, liability is limited to foreseeable direct loss and the value of the relevant order. The installer is responsible for safety rules, installation instructions and professional standards."] },
      { title: "9. Complaints and disputes", paragraphs: ["Complaints may be sent to info@pexxafloor.be. Consumers may contact the Belgian Consumer Mediation Service, Boulevard du Roi Albert II 8 box 1, 1000 Brussels (mediationconsommateur.be). Belgian law applies without depriving consumers of mandatory protection in their country of residence. Jurisdiction is determined by applicable law."] },
    ] },
    privacy: { title: "Privacy and GDPR policy", description: "This policy explains which personal data is processed, why, and what rights you have.", updated: "Last updated: 14 August 2026", sections: [
      { title: "Controller", paragraphs: [company.en, "For privacy questions or requests: info@pexxafloor.be."] },
      { title: "Data processed", items: ["Account and identity: name, email, identifier, login data and role.", "Orders and delivery: basket, products, prices, address, phone, history and status.", "PRO account: company, VAT number, activity, contact details and submitted documents.", "Quotes: configuration, project reference and customer information entered by the professional.", "Payment: identifiers and status supplied by Stripe; full card numbers are not stored.", "Technical data: security logs, IP address, device and language."] },
      { title: "Purposes and legal bases", items: ["Account, quotes, orders, delivery and support: contract or pre-contractual measures.", "Invoices, accounting, guarantees and authorities: legal obligation.", "Security, fraud prevention and service improvement: legitimate interests balanced against individual rights.", "Optional saved addresses and non-essential features: consent where required."] },
      { title: "Recipients", paragraphs: ["Authorised PexxaFloor staff and, as needed, Supabase, Vercel, Stripe, Resend, Google Maps, carriers, accountants and legally authorised bodies receive only the data needed for their role."] },
      { title: "International transfers", paragraphs: ["Where providers process data outside the EEA, transfers must rely on an adequacy decision, standard contractual clauses or another GDPR-recognised safeguard."] },
      { title: "Retention", paragraphs: ["Data is retained only as long as needed. Order, invoice and accounting records are retained for the applicable statutory period, generally up to ten years. Accounts are retained while active and later deleted or anonymised unless required for law or disputes. Optional addresses remain until the customer deletes them."] },
      { title: "Your rights", paragraphs: ["Where legal conditions are met, you may request access, correction, deletion, restriction, portability or object, and withdraw consent without retroactive effect. You may complain to the Belgian Data Protection Authority: dataprotectionauthority.be."] },
      { title: "Security", paragraphs: ["Measures include role controls, Supabase RLS policies, encrypted communications, server-side secrets and restricted access. Incidents are handled in accordance with applicable obligations."] },
    ] },
    cookies: { title: "Cookie policy", description: "Information about local storage and third-party services used by PexxaFloor.", updated: "Last updated: 14 August 2026", sections: [
      { title: "What are cookies?", paragraphs: ["Cookies and similar storage allow a website to remember information in a browser. Some are essential for login, security and the basket; others require prior consent."] },
      { title: "Necessary technologies", items: ["Supabase Auth for secure sessions and token renewal.", "Browser local storage to retain basket items.", "Language preference and technical security mechanisms."] },
      { title: "Third-party services", items: ["Stripe may use technologies needed to secure payment when checkout is opened.", "Google Maps Places receives address-field queries and may use its own cookies or identifiers.", "Vercel and Supabase may create security and availability logs."] },
      { title: "Your choice", paragraphs: ["Strictly necessary technologies cannot be disabled through the website. Non-essential technologies must only be enabled after consent where required by law. Browser settings can block or delete cookies, but some functions may no longer work."] },
      { title: "Contact", paragraphs: ["Questions about cookies or your rights: info@pexxafloor.be."] },
    ] },
    withdrawal: { title: "Withdrawal and returns", description: "Information for consumers wishing to return a distance order.", updated: "Last updated: 14 August 2026", sections: [
      { title: "Withdrawal period", paragraphs: ["Consumers generally have 14 days from the day they or a nominated third party physically receive the goods. For separately delivered goods, the period starts when the last item is received."] },
      { title: "How to withdraw", paragraphs: ["Before the deadline, send an unambiguous statement to info@pexxafloor.be with the order number. The model below is optional."] },
      { title: "Model form", paragraphs: ["To Unisis Development SRL / PexxaFloor, Brusselstraat 107 D, 1702 Groot-Bijgaarden, info@pexxafloor.be:\n\nI hereby give notice that I withdraw from my contract of sale of the following goods: [products].\nOrdered on / received on: [date].\nName: [name].\nAddress: [address].\nDate: [date].\nSignature, only for a paper form: [signature]."] },
      { title: "Return and refund", paragraphs: ["Goods must be returned within 14 days after notice, suitably protected and if possible in the original packaging. Direct return costs are borne by you unless agreed otherwise. The refund includes payments received and, where required by law, standard delivery. It may be withheld until the goods or proof of dispatch are received."] },
      { title: "Diminished value and exceptions", paragraphs: ["You are responsible for diminished value caused by handling beyond what is needed to inspect the goods. Statutory exclusions apply, including genuinely made-to-specification or clearly personalised goods. Contact us before returning goods to confirm practical arrangements."] },
    ] },
  },
  nl: {
    legal: { title: "Wettelijke vermeldingen", description: "Informatie over de uitgever, hosting en het gebruik van de PexxaFloor-website.", updated: "Laatst bijgewerkt: 14 augustus 2026", sections: [
      { title: "Uitgever en verkoper", paragraphs: [company.nl, "De verkoper is via bovenstaande gegevens bereikbaar voor vragen over de website, producten of een bestelling."] },
      { title: "Hosting", paragraphs: ["De website wordt gehost door Vercel Inc. Applicatiegegevens worden onder meer verwerkt via Supabase. Technische dienstverleners worden geregeld zoals beschreven in het privacybeleid."] },
      { title: "Intellectuele eigendom", paragraphs: ["Teksten, beelden, logo’s, configuratoren, documenten en website-elementen zijn beschermd. Reproductie, aanpassing of gebruik zonder voorafgaande schriftelijke toestemming is verboden, behalve waar de wet dit toestaat."] },
      { title: "Beschikbaarheid en aansprakelijkheid", paragraphs: ["PexxaFloor streeft naar correcte informatie en een beschikbare website. Onderbrekingen, technische fouten of kennelijk onjuiste informatie kunnen voorkomen. Technische informatie vervangt geen professionele studie wanneer het project die vereist."] },
      { title: "Externe diensten", paragraphs: ["De website gebruikt of verwijst naar diensten zoals Stripe, Google Maps, Supabase en Resend. Hun eigen voorwaarden kunnen van toepassing zijn."] },
    ] },
    terms: { title: "Algemene verkoopvoorwaarden", description: "Voorwaarden voor bestellingen bij PexxaFloor door consumenten en professionele klanten.", updated: "Van toepassing vanaf 14 augustus 2026", sections: [
      { title: "1. Verkoper en toepassingsgebied", paragraphs: [company.nl, "Deze voorwaarden regelen verkopen via de website. Dwingende consumentenbescherming geldt alleen voor klanten die buiten hun beroepsactiviteit handelen. Uitdrukkelijk overeengekomen bijzondere voorwaarden hebben voorrang bij tegenstrijdigheid."] },
      { title: "2. Producten en configurator", paragraphs: ["De essentiële kenmerken staan op de productpagina’s. De packconfigurator berekent een samenstelling op basis van de ingevoerde gegevens. De klant blijft verantwoordelijk voor correcte afmetingen, instellingen en beperkingen en vraagt bij technische twijfel advies vóór bestelling."] },
      { title: "3. Prijzen", paragraphs: ["Prijzen worden in euro exclusief en inclusief btw weergegeven waar van toepassing. Totaal, belastingen en leveringskosten worden vóór bevestiging getoond. Toekomstige prijzen kunnen wijzigen; de bevestigde prijs geldt behoudens een kennelijke fout."] },
      { title: "4. Bestelling en betaling", paragraphs: ["De klant controleert winkelwagen, identiteit en adres vóór betaling. De bestelling wordt bindend na betalings- en orderbevestiging, onder voorbehoud van beschikbaarheid en gebruikelijke fraudecontroles. Stripe verwerkt de betaling; PexxaFloor ontvangt geen volledige kaartgegevens."] },
      { title: "5. Levering", paragraphs: ["Zones, methoden, kosten en geschatte termijnen worden op de website of vóór betaling vermeld. Termijnen zijn indicatief tenzij uitdrukkelijk gegarandeerd. De klant verstrekt een toegankelijk adres, controleert pakketten en meldt zichtbare schade of ontbrekende artikelen snel met foto’s en orderreferentie."] },
      { title: "6. Herroeping door consumenten", paragraphs: ["Consumenten hebben doorgaans 14 dagen na ontvangst om de herroeping te melden en vervolgens 14 dagen om terug te sturen. Rechtstreekse retourkosten zijn voor de consument tenzij anders vermeld. Wettelijke uitzonderingen omvatten goederen volgens consumentenspecificaties of duidelijk gepersonaliseerde goederen; standaardopties kiezen maakt een product niet automatisch gepersonaliseerd."] },
      { title: "7. Garanties", paragraphs: ["Consumenten genieten de Belgische wettelijke conformiteitsgarantie, doorgaans twee jaar na levering van nieuwe goederen. Normale slijtage, foutieve installatie, onaangepast gebruik en latere schade vallen er niet onder. Professionele klanten genieten de dwingende en eventuele fabrieksgaranties."] },
      { title: "8. Aansprakelijkheid", paragraphs: ["Aansprakelijkheid die wettelijk niet kan worden uitgesloten blijft bestaan. Voor professionele klanten is de aansprakelijkheid, binnen de wet, beperkt tot voorzienbare rechtstreekse schade en de waarde van de betrokken bestelling. De installateur is verantwoordelijk voor veiligheid, instructies en vakregels."] },
      { title: "9. Klachten en geschillen", paragraphs: ["Klachten kunnen naar info@pexxafloor.be. Consumenten kunnen de Consumentenombudsdienst contacteren, Koning Albert II-laan 8 bus 1, 1000 Brussel (consumentenombudsdienst.be). Belgisch recht geldt zonder dwingende bescherming van het woonland van de consument weg te nemen. De bevoegde rechter volgt de toepasselijke wettelijke regels."] },
    ] },
    privacy: { title: "Privacy- en AVG-beleid", description: "Dit beleid legt uit welke persoonsgegevens worden verwerkt, waarom en welke rechten u hebt.", updated: "Laatst bijgewerkt: 14 augustus 2026", sections: [
      { title: "Verwerkingsverantwoordelijke", paragraphs: [company.nl, "Voor privacyvragen of verzoeken: info@pexxafloor.be."] },
      { title: "Verwerkte gegevens", items: ["Account en identiteit: naam, e-mail, identificator, inloggegevens en rol.", "Bestelling en levering: winkelwagen, producten, prijzen, adres, telefoon, geschiedenis en status.", "PRO-account: onderneming, btw-nummer, activiteit, contactgegevens en documenten.", "Offertes: configuratie, projectreferentie en door de professional ingevoerde klantgegevens.", "Betaling: identificatoren en status van Stripe; volledige kaartnummers worden niet bewaard.", "Technische gegevens: beveiligingslogs, IP-adres, toestel en taal."] },
      { title: "Doeleinden en rechtsgronden", items: ["Account, offertes, bestelling, levering en nazorg: overeenkomst of precontractuele maatregelen.", "Facturatie, boekhouding, garanties en overheden: wettelijke verplichting.", "Beveiliging, fraudepreventie en verbetering: gerechtvaardigd belang na belangenafweging.", "Optionele opgeslagen adressen en niet-essentiële functies: toestemming waar vereist."] },
      { title: "Ontvangers", paragraphs: ["Bevoegde PexxaFloor-medewerkers en, indien nodig, Supabase, Vercel, Stripe, Resend, Google Maps, vervoerders, boekhouders en bevoegde overheden ontvangen enkel noodzakelijke gegevens."] },
      { title: "Internationale doorgiften", paragraphs: ["Verwerking buiten de EER moet steunen op een adequaatheidsbesluit, standaardcontractbepalingen of een andere erkende AVG-waarborg."] },
      { title: "Bewaartermijnen", paragraphs: ["Gegevens worden niet langer bewaard dan nodig. Bestel-, factuur- en boekhoudgegevens worden gedurende de toepasselijke wettelijke termijn bewaard, doorgaans tot tien jaar. Accounts worden tijdens hun activiteit bewaard en later verwijderd of geanonimiseerd, behoudens wettelijke plicht of geschil. Optionele adressen blijven tot de klant ze verwijdert."] },
      { title: "Uw rechten", paragraphs: ["Wanneer de wettelijke voorwaarden vervuld zijn, kunt u inzage, verbetering, verwijdering, beperking, overdraagbaarheid of bezwaar vragen en toestemming zonder terugwerkende kracht intrekken. U kunt klacht indienen bij de Belgische Gegevensbeschermingsautoriteit: gegevensbeschermingsautoriteit.be."] },
      { title: "Beveiliging", paragraphs: ["Maatregelen omvatten rolcontrole, Supabase RLS, versleutelde communicatie, server-side geheimen en beperkte toegang. Incidenten worden volgens de toepasselijke verplichtingen behandeld."] },
    ] },
    cookies: { title: "Cookiebeleid", description: "Informatie over lokale opslag en externe diensten die PexxaFloor gebruikt.", updated: "Laatst bijgewerkt: 14 augustus 2026", sections: [
      { title: "Wat zijn cookies?", paragraphs: ["Cookies en vergelijkbare opslag laten een website informatie in de browser onthouden. Sommige zijn noodzakelijk voor login, beveiliging en winkelwagen; andere vereisen voorafgaande toestemming."] },
      { title: "Noodzakelijke technologieën", items: ["Supabase Auth voor veilige sessies en tokenvernieuwing.", "Lokale browseropslag om winkelwagenartikelen te bewaren.", "Taalvoorkeur en technische beveiligingsmechanismen."] },
      { title: "Externe diensten", items: ["Stripe kan noodzakelijke technologie gebruiken wanneer de betaalpagina wordt geopend.", "Google Maps Places ontvangt zoekopdrachten in het adresveld en kan eigen cookies of identificatoren gebruiken.", "Vercel en Supabase kunnen beveiligings- en beschikbaarheidslogs maken."] },
      { title: "Uw keuze", paragraphs: ["Strikt noodzakelijke technologie kan niet via de website worden uitgeschakeld. Niet-essentiële technologie mag waar wettelijk vereist pas na toestemming worden geactiveerd. Via browserinstellingen kunt u cookies blokkeren of verwijderen, maar functies kunnen daardoor wegvallen."] },
      { title: "Contact", paragraphs: ["Vragen over cookies of uw rechten: info@pexxafloor.be."] },
    ] },
    withdrawal: { title: "Herroeping en retour", description: "Informatie voor consumenten die een bestelling op afstand willen retourneren.", updated: "Laatst bijgewerkt: 14 augustus 2026", sections: [
      { title: "Herroepingstermijn", paragraphs: ["Consumenten beschikken doorgaans over 14 dagen vanaf de fysieke ontvangst door henzelf of een aangewezen derde. Bij afzonderlijke leveringen begint de termijn bij ontvangst van het laatste goed."] },
      { title: "Hoe herroepen", paragraphs: ["Stuur vóór het einde van de termijn een ondubbelzinnige verklaring met ordernummer naar info@pexxafloor.be. Onderstaand model is niet verplicht."] },
      { title: "Modelformulier", paragraphs: ["Aan Unisis Development SRL / PexxaFloor, Brusselstraat 107 D, 1702 Groot-Bijgaarden, info@pexxafloor.be:\n\nHierbij deel ik mee dat ik mijn overeenkomst betreffende de verkoop van de volgende goederen herroep: [producten].\nBesteld op / ontvangen op: [datum].\nNaam: [naam].\nAdres: [adres].\nDatum: [datum].\nHandtekening, alleen bij papieren verzending: [handtekening]."] },
      { title: "Retour en terugbetaling", paragraphs: ["Goederen moeten uiterlijk 14 dagen na de melding goed beschermd en indien mogelijk in de originele verpakking worden teruggestuurd. Rechtstreekse retourkosten zijn voor u tenzij anders overeengekomen. De terugbetaling omvat ontvangen betalingen en, waar wettelijk vereist, standaardlevering. Ze mag worden uitgesteld tot ontvangst van de goederen of verzendbewijs."] },
      { title: "Waardevermindering en uitzonderingen", paragraphs: ["U bent aansprakelijk voor waardevermindering door meer behandeling dan nodig om de goederen te inspecteren. Wettelijke uitzonderingen gelden, waaronder werkelijk op specificatie gemaakte of duidelijk gepersonaliseerde goederen. Neem vóór retour contact op om de praktische regeling te bevestigen."] },
    ] },
  },
};

export function getLegalContent(locale: string, key: LegalDocumentKey) {
  const safeLocale = locale === "fr" || locale === "nl" ? locale : "en";
  return content[safeLocale][key];
}
